// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDONEuoxLkmzcaXy3MTI7JuY9MBxOHB1OY',
    appId: '1:643377509802:web:a38dd035075e0c1a0367d3',
    messagingSenderId: '643377509802',
    projectId: 'gout-app-1c271',
    authDomain: 'gout-app-1c271.firebaseapp.com',
    storageBucket: 'gout-app-1c271.appspot.com',
    measurementId: 'G-X2FT9X7S67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeu-dIqFCqX5QL42O85IlVJRJhwfiAHZM',
    appId: '1:643377509802:android:a9fdd6a8585922410367d3',
    messagingSenderId: '643377509802',
    projectId: 'gout-app-1c271',
    storageBucket: 'gout-app-1c271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyrvr2aWabKF8jeCLiwVIU3R-dAcHhPc',
    appId: '1:643377509802:ios:8c5e3ff7f9fc69f60367d3',
    messagingSenderId: '643377509802',
    projectId: 'gout-app-1c271',
    storageBucket: 'gout-app-1c271.appspot.com',
    androidClientId: '643377509802-2ss0grn7l6t3seeiplkig54t5do3rgdt.apps.googleusercontent.com',
    iosClientId: '643377509802-g8ak5gddtshh87surkpbdso3piddnsbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.goutApp',
  );
}
